Added additional technical edits for Partner Manager 2.9
mulesoft/docs-partner-manager pull request #146
Opened 2021-11-08 20:11 UTC by dhirsch1

2021-11-09 21:34 UTC, vijayang requested changes

2021-11-09 21:34 UTC, vijayang commented on modules/ROOT/pages/file-name-pattern.adoc
> +|${ICN} |Group Control Number
Please change ${ICN} to ${GCN}

2021-11-09 21:34 UTC, vijayang commented on modules/ROOT/pages/file-name-pattern.adoc
>  |`INVOICE_MYTHICALSUPPLIERS_12355343.XML`
Please change "XML" to "xml"

2021-11-09 21:34 UTC, vijayang commented on modules/ROOT/pages/file-name-pattern.adoc
>  |`850_NTORETAIL_20201102_192655521_300001.JSON`
Please change "JSON" to "json"

2021-11-11 18:20 UTC, vijayang submitted a review, later dismissed

2021-11-11 18:58 UTC, sathya0 approved these changes, later dismissed

2021-11-11 18:58 UTC, sathya0 commented on modules/ROOT/pages/setup-payload-storage-API.adoc
> +* *Payload view URL*: (Optional) A secondary payload storage API URL that you can use to view the payload on the Activity page if the payload storage API is restricted to your internal network.
```suggestion
* *Payload view URL*: (Optional) A secondary payload storage API URL that you can use to view the payload on the *Activity* page if the payload storage API is restricted to your internal network.
```

2021-11-11 18:58 UTC, sathya0 commented on modules/ROOT/pages/setup-payload-storage-API.adoc
> +* *Payload view URL*: (Optional) A secondary payload storage API URL that you can use to view the payload on the Activity page if the payload storage API is restricted to your internal network.
```suggestion
* *Payload view URL*: (Optional) A secondary payload storage API URL that you can use to view the payload on the Activity page if the payload storage API is restricted to your internal network
```

2021-11-11 19:02 UTC, sathya0 approved these changes

2021-11-11 19:03 UTC, merged