Partner Manager v2.10
mulesoft/docs-partner-manager pull request #150
Opened 2021-12-10 18:44 UTC by dhirsch1

2021-12-16 07:13 UTC, vijayang requested changes

2021-12-16 07:13 UTC, vijayang commented on modules/ROOT/pages/endpoint-as2-send.adoc
> +Does not require backend applications to authenticate when connecting to this endpoint.
AS2 send endpoints are interfaces with partners and not backend applications. We should change this as below.
"No additional authentication is requires to send messages to the partner's AS2 endpoint"

2021-12-16 07:13 UTC, vijayang commented on modules/ROOT/pages/endpoint-as2-send.adoc
> +Requires backend applications to use the username and password provided by your partner to connect to this endpoint. Enter this information in the *Username* and *Password* fields.
Please change as following:
Your partner requires you to pass basic authentication credentials (username and password) when sending messages to the AS2 endpoint. Enter this information in the *Username* and *Password* fields.

2021-12-16 14:39 UTC, vijayang approved these changes

2021-12-17 19:09 UTC, sathya0 approved these changes

2021-12-17 20:54 UTC, merged