Partner Manager 2.11 with a rewritten Activity Tracking topic
mulesoft/docs-partner-manager pull request #163
Opened 2022-04-14 18:06 UTC by dhirsch1

2022-04-20 05:22 UTC, vijayang requested changes

2022-04-20 05:22 UTC, vijayang commented on modules/ROOT/pages/activity-tracking.adoc
> +* Message type, such as `my-po-ack:ORD-9892330`
The first filter with the label "Type", is actually direction - with dropdown menu options "Receive from partners" and "Send to partners".

2022-04-20 05:22 UTC, vijayang commented on modules/ROOT/pages/activity-tracking.adoc
> +* Message type, such as `mythical-po-ack-ORD-9892330`
Message type, such as `mythical-po-ack"

The ORD-9892330 is the business Key value (such as order number)

2022-04-20 05:22 UTC, vijayang commented on modules/ROOT/pages/activity-tracking.adoc
> +| View and download the MDN message sent to the partner
View and download the MDN message sent to the partner for inbound AS2 transmissions.

2022-04-20 05:22 UTC, vijayang commented on modules/ROOT/pages/activity-tracking.adoc
> +| View and download the MDN received from the partner
View and download the MDN received from the partner in response to outbound AS2 transmissions.

2022-04-20 05:22 UTC, vijayang commented on modules/ROOT/pages/activity-tracking.adoc
> +|View and download the payload received from the partner (*Vijay, is this correct? How do users see the metadata for an inbound message?*)
Yes - this is correct

2022-04-20 05:22 UTC, vijayang commented on modules/ROOT/pages/activity-tracking.adoc
> +. In the ??? field *Click *View payload*. (*Vijay, what is the name of this field? I only see the Waiting for CONTRL status here so I can't tell.*)
This is same as the experience in X12. 
In the *Sent transmission* field, click *View payload*.

2022-04-21 13:11 UTC, vijayang requested changes

2022-04-21 13:11 UTC, vijayang commented on modules/ROOT/pages/activity-tracking.adoc
> +. In the *Transmission Flow* section, click *View CONTRL*.
Please change as:
View and download the EDIFACT CONTRL or X12 997 acknowledgement message sent to the partner.

In the *Transmission Flow* section, click *View CONTRL* or *View 997*.

2022-04-21 13:11 UTC, vijayang commented on modules/ROOT/pages/activity-tracking.adoc
> +|View the CONTRL message received from the partner, if it exists
View the EDIFACT CONTRL or X12 997 acknowledgement message received from the partner, if it exists

2022-04-21 20:18 UTC, vijayang approved these changes, later dismissed

2022-04-21 20:22 UTC, IsaacEldridge commented on modules/ROOT/pages/edifact-send-settings.adoc
> +a|Indicates if the EDIFACT transaction set is for testing or production. *Vijay, is this still true? There is no default that shows up.*
no answer from Vijay?

2022-04-21 20:25 UTC, IsaacEldridge requested changes
see comment

2022-04-21 20:49 UTC, IsaacEldridge approved these changes

2022-04-21 20:50 UTC, merged