W-16126070 PM 2.20 doc updates
mulesoft/docs-partner-manager pull request #239
Opened 2024-07-15 19:58 UTC by tasmoore

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2024-07-22 05:20 UTC, vijayang requested changes

2024-07-22 05:20 UTC, vijayang commented on modules/ROOT/pages/as2-encoding.adoc
> +The Global AS2 encoding setting determines the character encoding type for all messages received from this partner.
Please remove "Global", as it is a partner specific configuration. 
Note: Just realized that the label does state "Global". We will change it to a more meaningful value in the next release. 2.20 will still go out with "Global" in the label.

2024-07-22 05:20 UTC, vijayang commented on modules/ROOT/pages/endpoint-ftp-receive.adoc
> +| Enables inbound endpoints to receive non UTF-8 encoded documents for XML, CSV, and X12 document types.
Please remove " for XML, CSV, and X12 document types.", as the config applies for all message formats including JSON and EDIFACT too. We do not have to mention the document types explicitly.

2024-07-23 20:04 UTC, vijayang approved these changes

2024-07-23 20:31 UTC, bjoson-mulesoft approved these changes

2024-07-24 21:38 UTC, merged