W-17312043 apm 2.21.0 doc updates
mulesoft/docs-partner-manager pull request #247
Opened 2024-12-03 18:23 UTC by tasmoore

# Writer's Quality Checklist

Before merging your PR, did you:

- [ ] Run spell checker
- [ ] Run link checker to check for broken xrefs
- [ ] Check for orphan files
- [ ] Perform a local build and do a final visual check of your content, including checking for:
  - Broken images
  - Dead links
  - Correct rendering of partials if they are used in your content
  - Formatting issues, such as:
    - Misnumbered ordered lists (steps) or incorrectly nested unordered lists
    - Messed up tables
    - Proper indentation
    - Correct header levels
- [ ] Receive final review and signoff from:
  - Technical SME
  - Product Manager
  - Editor or peer reviewer
  - Reporter, if this content is in response to a reported issue (internal or external feedback)
- [ ] If applicable, verify that the software actually got released

2025-01-20 15:17 UTC, vijayang requested changes
@tasmoore - Everything looks great.
Requested the 'cXML' specific sections to be removed as it is not part of 2.21. Let's save the content and use it in 2.22 docs.

2025-01-20 15:17 UTC, vijayang commented on modules/ROOT/pages/cloudhub-deployment-settings.adoc
> +If you process cXML messages with <DOCTYPE> tags, you must set the `minMuleVersion` to 4.5.0 or higher. If you're migrating from an earlier version, you must perform end-to-end regression testing on
@tasmoore - the Min Mule version config / cXML support is now part of 2.22. Please more this section.

2025-01-20 15:17 UTC, vijayang commented on modules/ROOT/pages/message-type-receive-from-partners.adoc
> +If you want to process cXML messages with <DOCTYPE> tags, you must set the `minMuleVersion` to 4.5.0 or higher and upgrade your runtime environment. For more information, see Partner Manager deployme
@tasmoore - Please remove this section as it now moved to 2.22.

2025-01-20 15:17 UTC, vijayang commented on modules/ROOT/pages/message-type-send-to-partners.adoc
> +If you want to process cXML messages with <DOCTYPE> tags, you must set the `minMuleVersion` to 4.5.0 or higher and upgrade your runtime environment. For more information, see Partner Manager deployme
@tasmoore  - Please remove this section as it now moved to 2.22.

2025-01-20 15:17 UTC, vijayang commented on modules/ROOT/pages/message-type-source-at-host.adoc
> +If you want to process cXML messages with <DOCTYPE> tags, you must set the `minMuleVersion` to 4.5.0 or higher and upgrade your runtime environment. For more information, see Partner Manager deployme
@tasmoore  - Please remove this section as it now moved to 2.22.

2025-01-20 15:17 UTC, vijayang commented on modules/ROOT/pages/message-type-target-at-host.adoc
> +If you want to process cXML messages with <DOCTYPE> tags, you must set the `minMuleVersion` to 4.5.0 or higher and upgrade your runtime environment. For more information, see Partner Manager deployme
@tasmoore  - Please remove this section as it now moved to 2.22.

2025-01-20 15:17 UTC, vijayang commented on modules/ROOT/pages/rtf-deployment-settings.adoc
> +(Uses 4.3.0)
@tasmoore  - Please remove this section as it now moved to 2.22.

2025-01-28 13:53 UTC, vijayang approved these changes

2025-01-28 17:32 UTC, marinasasso approved these changes

2025-01-29 00:02 UTC, merged